version: '3.7'

services:
    web:
        # use wait for it script to make sure db is ready before launching
        command: ["/scripts/boot.sh"]
        ports:
            - "8000:8000"
        volumes:
            - ./dtekportal:/code
            - ./scripts:/scripts
        environment:
            - DJANGO_DEBUG=1
